import test from"node:test";import assert from"node:assert/strict";import{mkdtemp}from"node:fs/promises";import os from"node:os";import path from"node:path";import{summarizeDate}from"../../local/src/summarizer.js";import{defaultConfig}from"../../local/src/config.js";
test("empty day returns NO_DATA and does not call API",async()=>{process.env.ODL_DATA_DIR=await mkdtemp(path.join(os.tmpdir(),"odl-empty-"));const cfg=structuredClone(defaultConfig);cfg.summary.provider="openai";assert.deepEqual(await summarizeDate("2026-09-17",cfg),{status:"NO_DATA"})});

import{mkdir,writeFile}from"node:fs/promises";
import{resolveScheduledDate}from"../../local/src/summarizer.js";
async function put(root:string,relative:string,value:unknown){const file=path.join(root,"data",relative);await mkdir(path.dirname(file),{recursive:true});await writeFile(file,typeof value==="string"?value:JSON.stringify(value,null,2),"utf8")}
const event=(at:string,baseline=false)=>JSON.stringify({type:"message_seen",message_key:`key-${at}`,baseline,last_seen_at:at})+"\n";
test("scheduled resolver selects only newest eligible activity date and skips empty files",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"odl-scheduled-"));process.env.ODL_DATA_DIR=root;const cfg=structuredClone(defaultConfig);await put(root,"events/2026-09-15.jsonl",event("2026-09-15T10:00:00Z"));await put(root,"events/2026-09-17.jsonl",event("2026-09-17T10:00:00Z"));await put(root,"events/2026-09-19.jsonl",event("2026-09-19T10:00:00Z",true));await put(root,"manual-notes/2026-09-20.jsonl","");assert.equal(await resolveScheduledDate(cfg,new Date("2026-09-21T07:00:00+09:00")),"2026-09-17")});
test("scheduled resolver returns NO_DATA candidate when all activity is successfully summarized",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"odl-complete-"));process.env.ODL_DATA_DIR=root;const cfg=structuredClone(defaultConfig);await put(root,"events/2026-09-17.jsonl",event("2026-09-17T10:00:00Z"));await put(root,"summary-state/2026-09-17.json",{date:"2026-09-17",status:"success",generated_at:"2026-09-18T00:00:00Z"});assert.equal(await resolveScheduledDate(cfg,new Date("2026-09-21T07:00:00+09:00")),null)});
test("manual note or recovered activity newer than summary makes a past date eligible",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"odl-dirty-"));process.env.ODL_DATA_DIR=root;const cfg=structuredClone(defaultConfig);await put(root,"manual-notes/2026-09-17.jsonl",JSON.stringify({content:"recovered note",created_at:"2026-09-20T10:00:00Z"})+"\n");await put(root,"summary-state/2026-09-17.json",{date:"2026-09-17",status:"success",generated_at:"2026-09-18T00:00:00Z"});assert.equal(await resolveScheduledDate(cfg,new Date("2026-09-21T07:00:00+09:00")),"2026-09-17")});
test("today is never a scheduled candidate",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"odl-today-"));process.env.ODL_DATA_DIR=root;const cfg=structuredClone(defaultConfig);await put(root,"events/2026-09-21.jsonl",event("2026-09-21T01:00:00Z"));assert.equal(await resolveScheduledDate(cfg,new Date("2026-09-21T07:00:00+09:00")),null)});
