import http, { type IncomingMessage, type ServerResponse } from "node:http"; import { getAuthToken,tokenMatches } from "./auth.js"; import { loadConfig,saveConfig } from "./config.js"; import { manualNoteSchema,snapshotSchema } from "../../shared/src/schemas.js"; import { saveSnapshot } from "./conversations.js"; import { appendJsonl,readJsonl } from "./storage.js"; import { logicalDate,resolveDate } from "./time.js"; import { summarizeDate } from "./summarizer.js"; import { VERSION } from "../../shared/src/constants.js"; import { validateVault } from "./obsidian.js"; import { log } from "./logger.js";
const send=(res:ServerResponse,status:number,data:unknown)=>{res.writeHead(status,{"Content-Type":"application/json; charset=utf-8"});res.end(JSON.stringify(data))};
async function body(req:IncomingMessage):Promise<unknown>{const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>2_000_000)throw new Error("Payload too large");chunks.push(chunk)}return JSON.parse(Buffer.concat(chunks).toString("utf8")||"{}");}
export async function createServer():Promise<http.Server>{const token=await getAuthToken();return http.createServer(async(req,res)=>{try{const origin=req.headers.origin;if(origin&& !origin.startsWith("chrome-extension://")){send(res,403,{ok:false,error:"CORS origin rejected"});return}if(origin)res.setHeader("Access-Control-Allow-Origin",origin);if(req.method==="OPTIONS"){res.writeHead(204,{"Access-Control-Allow-Headers":"Content-Type, X-ODL-Token","Access-Control-Allow-Methods":"GET, POST, PUT","Vary":"Origin"});res.end();return}if(!tokenMatches(req.headers["x-odl-token"] as string|undefined,token)){send(res,401,{ok:false,code:"AUTH_FAILED",error:"Unauthorized"});return}const cfg=await loadConfig(),url=new URL(req.url||"/","http://127.0.0.1");
if(req.method==="GET"&&url.pathname==="/api/health")return send(res,200,{ok:true,version:VERSION,time:new Date().toISOString()});
if(req.method==="POST"&&url.pathname==="/api/snapshot"){const value=snapshotSchema.parse(await body(req));const saved=await saveSnapshot(value,cfg);await log("INFO",`Saved snapshot conversation=${saved.conversation_id} messages=${saved.messages.length}`);return send(res,200,{ok:true});}
if(req.method==="POST"&&url.pathname==="/api/manual-note"){const value=manualNoteSchema.parse(await body(req)),date=logicalDate(new Date(value.created_at),cfg.timezone,cfg.summary.dayBoundaryHour),existing=await readJsonl<{id:string}>("manual-notes",date);if(!existing.some(x=>x.id===value.id))await appendJsonl("manual-notes",date,value);return send(res,201,{ok:true});}
if(req.method==="GET"&&url.pathname==="/api/config")return send(res,200,cfg);
if(req.method==="PUT"&&url.pathname==="/api/config")return send(res,200,await saveConfig(await body(req)));
if(req.method==="POST"&&url.pathname==="/api/summarize"){const value=await body(req) as {date?:string};return send(res,200,await summarizeDate(resolveDate(value.date||"today",cfg.timezone,cfg.summary.dayBoundaryHour),cfg));}
if(req.method==="GET"&&url.pathname==="/api/today"){const date=resolveDate("today",cfg.timezone,cfg.summary.dayBoundaryHour),events=await readJsonl<{conversation_id:string}>("events",date),notes=await readJsonl("manual-notes",date);return send(res,200,{ok:true,date,conversations:new Set(events.map(x=>x.conversation_id)).size,notes:notes.length});}
if(req.method==="POST"&&url.pathname==="/api/test-vault")return send(res,200,{ok:true,...await validateVault(cfg.obsidian.vaultPath)});send(res,404,{ok:false,error:"Not found"});}catch(e){await log("ERROR","Request failed",e);const msg=e instanceof Error?e.message:"Request failed";send(res,msg.includes("Unauthorized")?401:400,{ok:false,error:msg.split("\n")[0]})}})}
export async function startServer():Promise<void>{const cfg=await loadConfig();if(cfg.server.host!=="127.0.0.1")throw new Error("CONFIG_ERROR: server host must be 127.0.0.1");const server=await createServer();server.listen(cfg.server.port,cfg.server.host,()=>{void log("INFO",`Service listening host=${cfg.server.host} port=${cfg.server.port}`)});}
if(process.argv[1]&&import.meta.url===new URL(`file://${process.argv[1].replace(/\\/g,"/")}`).href)void startServer();
