export * from "./schemas.js";
export type ErrorCode = "CHATGPT_PARSE_ERROR" | "LOCAL_SERVICE_UNREACHABLE" | "AUTH_FAILED" | "VAULT_NOT_FOUND" | "VAULT_NOT_WRITABLE" | "OPENAI_API_ERROR" | "OPENAI_SCHEMA_ERROR" | "DAILY_NOTE_WRITE_ERROR" | "CONFIG_ERROR";
